name: Build Magisk Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip android-ndk-r23b-linux.zip

      - name: Build Module
        run: |
          bash build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: magisk-overlayfs-module
          path: out/magisk_overlayfs_*.zip
